create table doctor (
	emp_id INT,
	name VARCHAR(50),
	specialization VARCHAR(18),
	dep_id INT references department(dep_id),
    primary key(emp_id)
);
insert into doctor (emp_id, name, specialization, dep_id) values (20, 'Benito', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (89, 'Cheston', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (64, 'Lorne', 'Obstetrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (85, 'Carmine', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (19, 'Halley', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (95, 'Ragnar', 'Gynecologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (81, 'Gabie', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (24, 'Kym', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (49, 'Rasia', 'Obstetrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (15, 'Dwight', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (43, 'Marian', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (3, 'Cherise', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (89, 'Mela', 'Cardiologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (68, 'Sheff', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (9, 'Addy', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (40, 'Irv', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (85, 'Ibrahim', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (15, 'Eleni', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (11, 'Rafaelia', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (11, 'Jyoti', 'Cardiologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (12, 'Hatti', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (89, 'Jodi', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (61, 'Sigismondo', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (7, 'Antonetta', 'Neurologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (42, 'Giorgio', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (79, 'Raleigh', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (79, 'Frazier', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (29, 'Cordie', 'Gynecologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (65, 'Francisca', 'Gynecologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (43, 'Vivia', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (67, 'Caz', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (7, 'Tabor', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (46, 'Clarissa', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (43, 'Pammie', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (16, 'Eddy', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (77, 'Addy', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (94, 'Willem', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (56, 'Aleece', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (42, 'Matthiew', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (19, 'Boonie', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (79, 'Hube', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (48, 'Molly', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (49, 'Puff', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (39, 'Kym', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (18, 'Zebulen', 'Neurologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (89, 'Branden', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (30, 'Betta', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (50, 'Bev', 'Oncologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (55, 'Samantha', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (25, 'Keen', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (97, 'Barrett', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (4, 'Cyrill', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (19, 'Pippa', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (39, 'Teirtza', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (58, 'Millard', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (59, 'Weylin', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (56, 'Morrie', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (72, 'Elfrida', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (52, 'Torrin', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (18, 'Melba', 'Psychiatrist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (70, 'Benedikt', 'Psychiatrist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (89, 'Felipe', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (70, 'Kelley', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (91, 'Cathleen', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (43, 'Orelee', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (85, 'Boothe', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (94, 'Elizabeth', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (5, 'Maire', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (64, 'Tanny', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (60, 'Durant', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (98, 'Goraud', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (88, 'Jasun', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (21, 'Mano', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (2, 'Derril', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (66, 'Jodie', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (56, 'Gale', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (52, 'Wald', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (94, 'Alaric', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (20, 'Chad', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (52, 'Elysee', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (44, 'Jordana', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (59, 'Hillie', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (74, 'Kristos', 'Oncologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (27, 'Anabelle', 'Oncologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (29, 'Garrick', 'Psychiatrist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (71, 'Aurelea', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (75, 'Vanya', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (1, 'Mahmud', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (36, 'Earvin', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (22, 'Daniela', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (59, 'Mordecai', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (66, 'Petr', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (32, 'Peadar', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (18, 'Lorine', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (35, 'Dahlia', 'Cardiologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (99, 'Jannel', 'Neurologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (64, 'Christiane', 'Obstetrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (100, 'Meg', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (10, 'Evangeline', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (7, 'Trula', 'Urologist', 2);