create table doctor (
	emp_id INT,
	name VARCHAR(50),
	specialization VARCHAR(18),
	dep_id INT references department(dep_id),
    primary key(emp_id)
);
insert into doctor (emp_id, name, specialization, dep_id) values (1, 'Benito', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (2, 'Cheston', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (3, 'Lorne', 'Obstetrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (4, 'Carmine', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (5, 'Halley', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (6, 'Ragnar', 'Gynecologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (7, 'Gabie', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (8, 'Kym', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (9, 'Rasia', 'Obstetrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (10, 'Dwight', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (11, 'Marian', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (12, 'Cherise', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (13, 'Mela', 'Cardiologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (14, 'Sheff', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (15, 'Addy', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (16, 'Irv', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (17, 'Ibrahim', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (18, 'Eleni', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (19, 'Rafaelia', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (20, 'Jyoti', 'Cardiologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (21, 'Hatti', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (22, 'Jodi', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (23, 'Sigismondo', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (24, 'Antonetta', 'Neurologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (25, 'Giorgio', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (26, 'Raleigh', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (27, 'Frazier', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (28, 'Cordie', 'Gynecologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (29, 'Francisca', 'Gynecologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (30 , 'Vivia', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (31, 'Caz', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (32, 'Tabor', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (33, 'Clarissa', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (34, 'Pammie', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (35, 'Eddy', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (36, 'Addy', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (37, 'Willem', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (38, 'Aleece', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (39, 'Matthiew', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (40, 'Boonie', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (41, 'Hube', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (42, 'Molly', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (43, 'Puff', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (44, 'Kym', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (45, 'Zebulen', 'Neurologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (46, 'Branden', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (47, 'Betta', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (48, 'Bev', 'Oncologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (49, 'Samantha', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (50, 'Keen', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (100, 'Barrett', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (99, 'Cyrill', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (98, 'Pippa', 'Ophthalmologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (97, 'Teirtza', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (96, 'Millard', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (95, 'Weylin', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (94, 'Morrie', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (93, 'Elfrida', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (92, 'Torrin', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (91, 'Melba', 'Psychiatrist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (90, 'Benedikt', 'Psychiatrist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (89, 'Felipe', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (88, 'Kelley', 'Orthopedic Surgeon', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (87, 'Cathleen', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (86, 'Orelee', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (85, 'Boothe', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (84, 'Elizabeth', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (83, 'Maire', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (82, 'Tanny', 'Cardiologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (81, 'Durant', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (80, 'Goraud', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (79, 'Jasun', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (78, 'Mano', 'Gynecologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (77, 'Derril', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (76, 'Jodie', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (75, 'Gale', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (74, 'Wald', 'Obstetrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (73, 'Alaric', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (72, 'Chad', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (71, 'Elysee', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (70, 'Jordana', 'Urologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (69, 'Hillie', 'Dermatologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (68, 'Kristos', 'Oncologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (67, 'Anabelle', 'Oncologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (66, 'Garrick', 'Psychiatrist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (65, 'Aurelea', 'Oncologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (64, 'Vanya', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (63, 'Mahmud', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (62, 'Earvin', 'Neurologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (61, 'Daniela', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (60, 'Mordecai', 'Psychiatrist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (59, 'Petr', 'Pediatrician', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (58, 'Peadar', 'Pediatrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (57, 'Lorine', 'Urologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (56, 'Dahlia', 'Cardiologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (55, 'Jannel', 'Neurologist', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (54, 'Christiane', 'Obstetrician', 1);
insert into doctor (emp_id, name, specialization, dep_id) values (53, 'Meg', 'Ophthalmologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (52, 'Evangeline', 'Dermatologist', 2);
insert into doctor (emp_id, name, specialization, dep_id) values (51, 'Trula', 'Urologist', 2);