create table medicines (
	med_id INT,
	name VARCHAR(550)
);
insert into medicines (med_id, name) values (1, 'Quinidine Gluconate');
insert into medicines (med_id, name) values (2, 'TITANIUM DIOXIDE');
insert into medicines (med_id, name) values (3, 'lisinopril');
insert into medicines (med_id, name) values (4, 'Perindopril Erbumine');
insert into medicines (med_id, name) values (5, 'ARSENIC TRIOXIDE - MATRICARIA RECUTITA - ACONITUM NAPELLUS - PULSATILLA VULGARIS - MERCURIUS SOLUBILIS - SILICON DIOXIDE -');
insert into medicines (med_id, name) values (6, 'tetracaine hydrochloride');
insert into medicines (med_id, name) values (7, 'Lorazepam');
insert into medicines (med_id, name) values (8, 'MAGNESIUM CITRATE');
insert into medicines (med_id, name) values (9, 'CEFTRIAXONE');
insert into medicines (med_id, name) values (10, 'DIMETHICONE');
insert into medicines (med_id, name) values (11, 'DEXTROMETHORPHAN HYDROBROMIDE, GUAIFENESIN, and PHENYLEPHRINE HYDROCHLORIDE');
insert into medicines (med_id, name) values (12, 'glyburide');
insert into medicines (med_id, name) values (13, 'Promethazine Hydrochloride and Codeine Phosphate');
insert into medicines (med_id, name) values (14, 'Aluminum Hydroxide, Magnesium Hydroxide, Simethicone');
insert into medicines (med_id, name) values (15, 'acetaminophen, dextromethorphan hydrobromide and doxylamine succinate');
insert into medicines (med_id, name) values (16, 'Octinoxate, Octisalate, Avobenzone');
insert into medicines (med_id, name) values (17, 'meloxicam');
insert into medicines (med_id, name) values (18, 'ziprasidone hydrochloride');
insert into medicines (med_id, name) values (19, 'Phenol');
insert into medicines (med_id, name) values (20, 'Potassium Chloride');
insert into medicines (med_id, name) values (21, 'strophanthus hispidus');
insert into medicines (med_id, name) values (22, 'Diclofenac Epolamine');
insert into medicines (med_id, name) values (23, 'NEVIRAPINE');
insert into medicines (med_id, name) values (24, 'SALICYLIC ACID');
insert into medicines (med_id, name) values (25, 'Chlordiazepoxide Hydrochloride');
insert into medicines (med_id, name) values (26, 'Aluminum Chlorohydrate');
insert into medicines (med_id, name) values (27, 'Ibuprofen');
insert into medicines (med_id, name) values (28, 'Fusarium compactum');
insert into medicines (med_id, name) values (29, 'OCTINOXATE, OCTOCRYLENE, and TITANIUM DIOXIDE');
insert into medicines (med_id, name) values (30, 'Irbesartan');
insert into medicines (med_id, name) values (31, 'hydrocortisone acetate and pramoxine hydrochloride');
insert into medicines (med_id, name) values (32, 'LEVOFLOXACIN');
insert into medicines (med_id, name) values (33, 'Ibuprofen');
insert into medicines (med_id, name) values (34, 'Symphytum Officinale, Capsicum Annuum, Ledum Palustre, Colchicum Autumnale, Rhododendron Chrysanthum');
insert into medicines (med_id, name) values (35, 'Ibuprofen');
insert into medicines (med_id, name) values (36, 'Allantoin and Dimethicone');
insert into medicines (med_id, name) values (37, 'PREGABALIN');
insert into medicines (med_id, name) values (38, 'Bismuthum metallicum, Antimon.crud., Arg. nit., Arsenicum alb., Baptisia, Bryonia, Chamomilla, Cinchona, Iris versicolor, Kali bic., Lachesis, Lycopodium, Mag. carb., Nux vom., Phosphorus, Podoph. pelt., Pulsatilla, Raphanus, Rhus toxicodendron, Tabacum, Verbascum, Zingiber, Echinacea, Juglans regia');
insert into medicines (med_id, name) values (39, 'ATORVASTATIN CALCIUM');
insert into medicines (med_id, name) values (40, 'propranolol hydrochloride');
insert into medicines (med_id, name) values (41, 'Triclosan');
insert into medicines (med_id, name) values (42, 'temazepam');
insert into medicines (med_id, name) values (43, 'Tetracaine Hydrochloride');
insert into medicines (med_id, name) values (44, 'Sulfur');
insert into medicines (med_id, name) values (45, 'Naproxen');
insert into medicines (med_id, name) values (46, 'Terconazole');
insert into medicines (med_id, name) values (47, 'Hydrocodone Bitartrate and Acetaminophen');
insert into medicines (med_id, name) values (48, 'Oxcarbazepine');
insert into medicines (med_id, name) values (49, 'Ibuprofen');
insert into medicines (med_id, name) values (50, 'aliskiren hemifumarate and hydrochlorothiazide');
insert into medicines (med_id, name) values (51, 'UNDECYLENIC ACID');
insert into medicines (med_id, name) values (52, 'risperidone');
insert into medicines (med_id, name) values (53, 'spironolactone');
insert into medicines (med_id, name) values (54, 'Titanium Dioxide, Zinc Oxide');
insert into medicines (med_id, name) values (55, 'calcium carbonate');
insert into medicines (med_id, name) values (56, 'Dimethicone');
insert into medicines (med_id, name) values (57, 'Metronidazole');
insert into medicines (med_id, name) values (58, 'Aureobasidium pullulans');
insert into medicines (med_id, name) values (59, 'Fosphenytoin Sodium');
insert into medicines (med_id, name) values (60, 'Levetiracetam');
insert into medicines (med_id, name) values (61, 'CALCIUM CARBONATE');
insert into medicines (med_id, name) values (62, 'Atovaquone and Proguanil Hydrochloride');
insert into medicines (med_id, name) values (63, 'Venlafaxine Hydrochloride');
insert into medicines (med_id, name) values (64, 'Aluminum Zirconium Tetrachlorohydrex gly');
insert into medicines (med_id, name) values (65, 'Mineral oil, Petrolatum, Phenylephrine HCl, Shark liver oil');
insert into medicines (med_id, name) values (66, 'White Petrolatum');
insert into medicines (med_id, name) values (67, 'Enalapril Maleate');
insert into medicines (med_id, name) values (68, 'UNDECYLENIC ACID');
insert into medicines (med_id, name) values (69, 'Salicylic Acid and Glycolic Acid');
insert into medicines (med_id, name) values (70, 'Aspergillus fumigatus');
insert into medicines (med_id, name) values (71, 'Succinylcholine Chloride');
insert into medicines (med_id, name) values (72, 'Fluorecein sodium and Proparacaine Hydrochloride Opthahalmic Solution');
insert into medicines (med_id, name) values (73, 'lorazepam');
insert into medicines (med_id, name) values (74, 'Baptisia Tinctoria, Echinacea, Phytolacca Decandra, Aconitum Napellus, Arsenicum Album, Belladonna, Ferrum Phosphoricum');
insert into medicines (med_id, name) values (75, 'Octinoxate, Octisalate, Oxybenzone');
insert into medicines (med_id, name) values (76, 'OCTINOXATE, TITANIUM DIOXIDE, OCTISALATE, and OXYBENZONE');
insert into medicines (med_id, name) values (77, 'ALCOHOL');
insert into medicines (med_id, name) values (78, 'Tramadol Hydrochloride');
insert into medicines (med_id, name) values (79, 'Ethyl Alcohol');
insert into medicines (med_id, name) values (80, 'beclomethasone dipropionate');
insert into medicines (med_id, name) values (81, 'deferiprone');
insert into medicines (med_id, name) values (82, 'Sore Throat Spray');
insert into medicines (med_id, name) values (83, 'PAIN RELIEVING PLASTER');
insert into medicines (med_id, name) values (84, 'calcium carbonate');
insert into medicines (med_id, name) values (85, 'Allergenic Extracts Alum Precipitated');
insert into medicines (med_id, name) values (86, 'Titanium Dioxide');
insert into medicines (med_id, name) values (87, 'Sodium Fluoride');
insert into medicines (med_id, name) values (88, 'Clindamycin Hydrochloride');
insert into medicines (med_id, name) values (89, 'Terconazole');
insert into medicines (med_id, name) values (90, 'Dextroamphetamine Sulfate');
insert into medicines (med_id, name) values (91, 'Aspirin');
insert into medicines (med_id, name) values (92, 'isopropyl alcohol');
insert into medicines (med_id, name) values (93, 'Benzalkonium Chloride');
insert into medicines (med_id, name) values (94, 'fentanyl citrate');
insert into medicines (med_id, name) values (95, 'Diphenhydramine Hydrochloride');
insert into medicines (med_id, name) values (96, 'PRAVASTATIN SODIUM');
insert into medicines (med_id, name) values (97, 'OCTINOXATE, OCTISALATE');
insert into medicines (med_id, name) values (98, 'TITANIUM DIOXIDE');
insert into medicines (med_id, name) values (99, 'Methyldopa');
insert into medicines (med_id, name) values (100, 'OCTINOXATE, OXYBENZONE, ZINC OXIDE');